rootProject.name = "javaTests"
include("day2")
include("day3")
include("day7")
include("day4")
include("day5")
include("day8")
include("day9")
include("day10")
include("day11")
include("day12")
include("day13")
